SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE wp_t_scores;
TRUNCATE TABLE wp_t_questions;
SET FOREIGN_KEY_CHECKS = 1;
SHOW TABLE STATUS LIKE 'wp\_t\_%';

SELECT * FROM wp_posts WHERE post_type = 'wpt_test';

SET @test_id := (SELECT ID FROM wp_posts WHERE post_type = 'wpt_test' AND post_title = 'Eysenck’s Personality Inventory (EPI) (Extroversion/Introversion)' ORDER BY ID DESC LIMIT 1);
INSERT INTO wp_t_questions (test_id, question_title) VALUES
(@test_id, 'Do you often long for excitement?'),
(@test_id, 'Do you often need understanding friends to cheer you up?'),
(@test_id, 'Are you usually carefree?'),
(@test_id, 'Do you find it very hard to take no for an answer?'),
(@test_id, 'Do you stop and think things over before doing anything?'),
(@test_id, 'If you say you will do something do you always keep your promise,no matter how inconvenient it might be to do so?'),
(@test_id, 'Do your moods go up and down?'),
(@test_id, 'Do you generally do and say things quickly without stopping to think?'),
(@test_id, 'Do you ever feel ‘just miserable’ for no good reason?'),
(@test_id, 'Would you do almost anything for a dare?'),
(@test_id, 'Do you suddenly feel shy when you want to talk to an attractive stranger?'),
(@test_id, 'Once in a while do you lose your temper and get angry?'),
(@test_id, 'Do you often do things on the spur of the moment?'),
(@test_id, 'Do you often worry about things you should have done or said?'),
(@test_id, 'Generally do you prefer reading to meeting people?'),
(@test_id, 'Are your feelings rather easily hurt?'),
(@test_id, 'Do you like going out a lot?'),
(@test_id, 'Do you occasionally have thoughts and ideas that you would not like otherpeople to know about?'),
(@test_id, 'Are you sometimes bubbling over with energy and sometimes very sluggish?'),
(@test_id, 'Do you prefer to have few but special friends?'),
(@test_id, 'Do you daydream a lot?'),
(@test_id, 'When people shout at you do you shout back?'),
(@test_id, 'Are you often troubled about feelings of guilt?'),
(@test_id, 'Are all your habits good and desirable ones?'),
(@test_id, 'Can you usually let yourself go and enjoy yourself a lot at a lively party?'),
(@test_id, 'Would you call yourself tense or ‘highly strung’?'),
(@test_id, 'Do other people think of you as being very lively?'),
(@test_id, 'After you have done something important, do you come away feelingyou could have done better?'),
(@test_id, 'Are you mostly quiet when you are with other people?'),
(@test_id, 'Do you sometimes gossip?'),
(@test_id, 'Do ideas run through your head so that you cannot sleep?'),
(@test_id, 'If there is something you want to know about, would you rather look it upin a book than talk to someone about it?'),
(@test_id, 'Do you get palpitations or thumping in your hear?'),
(@test_id, 'Do you like the kind of work that you need to pay close attention to?'),
(@test_id, 'Do you get attacks of shaking or trembling?'),
(@test_id, 'Would you always declare everything at customs, even if you knewyou could never be found out?'),
(@test_id, 'Do you hate being with a crowd who play jokes on one another?'),
(@test_id, 'Are you an irritable person?'),
(@test_id, 'Do you like doing things in which you have to act quickly?'),
(@test_id, 'Do you worry about awful things that might happen?'),
(@test_id, 'Are you slow and unhurried in the way you move?'),
(@test_id, 'Have you ever been late for an appointment or work?'),
(@test_id, 'Do you have many nightmares?'),
(@test_id, 'Do you like talking to people so much that you never miss a chance of talking toa stranger?'),
(@test_id, 'Are you troubled by aches and pains?'),
(@test_id, 'Would you be very unhappy if you could not see lots of people most of the time?'),
(@test_id, 'Would you call yourself a nervous person?'),
(@test_id, 'Of all the people you know, are there some whom you definitely do not like?'),
(@test_id, 'Would you say that you were fairly self-confident?'),
(@test_id, 'Are you easily hurt when people find fault with you or your work?'),
(@test_id, 'Do you find it hard to really enjoy yourself at a lively party?'),
(@test_id, 'Are you troubled by feelings of inferiority?'),
(@test_id, 'Can you easily get some life into a dull party?'),
(@test_id, 'Do you sometimes talk about things you know nothing about?'),
(@test_id, 'Do you worry about your health?'),
(@test_id, 'Do you like playing pranks on others?'),
(@test_id, 'Do you suffer from sleeplessness?')

;
SELECT * FROM wp_t_questions;

SET @yes_id := (SELECT term_id FROM wp_terms WHERE name = 'Yes' ORDER BY term_id DESC);
SET @no_id  := (SELECT term_id FROM wp_terms WHERE name = 'No' ORDER BY term_id DESC);
SET @ei_id  := (SELECT term_id FROM wp_terms WHERE name = 'Extraversion/Introversion' ORDER BY term_id DESC);
SET @ns_id  := (SELECT term_id FROM wp_terms WHERE name = 'Neuroticism/Stability' ORDER BY term_id DESC);
SET @l_id   := (SELECT term_id FROM wp_terms WHERE name = 'Lie' ORDER BY term_id DESC);

INSERT INTO wp_t_scores (answer_id, question_id, scale_id, score_value) VALUES
(@yes_id, 1, @ei_id, 1),
(@yes_id, 2, @ns_id, 1),
(@yes_id, 3, @ei_id, 1),
(@yes_id, 4, @ns_id, 1),
(@no_id, 5, @ei_id, 1),
(@yes_id, 6, @l_id, 1),
(@yes_id, 7, @ns_id, 1),
(@yes_id, 8, @ei_id, 1),
(@yes_id, 9, @ns_id, 1),
(@yes_id, 10, @ei_id, 1),
(@yes_id, 11, @ns_id, 1),
(@no_id, 12, @l_id, 1),
(@yes_id, 13, @ei_id, 1),
(@yes_id, 14, @ns_id, 1),
(@no_id, 15, @ei_id, 1),
(@yes_id, 16, @ns_id, 1),
(@yes_id, 17, @ei_id, 1),
(@no_id, 18, @l_id, 1),
(@yes_id, 19, @ns_id, 1),
(@no_id, 20, @ei_id, 1),
(@yes_id, 21, @ns_id, 1),
(@yes_id, 22, @ei_id, 1),
(@yes_id, 23, @ns_id, 1),
(@yes_id, 24, @l_id, 1),
(@yes_id, 25, @ei_id, 1),
(@yes_id, 26, @ns_id, 1),
(@yes_id, 27, @ei_id, 1),
(@yes_id, 28, @ns_id, 1),
(@no_id, 29, @ei_id, 1),
(@no_id, 30, @l_id, 1),
(@yes_id, 31, @ns_id, 1),
(@no_id, 32, @ei_id, 1),
(@yes_id, 33, @ns_id, 1),
(@no_id, 34, @ei_id, 1),
(@yes_id, 35, @ns_id, 1),
(@yes_id, 36, @l_id, 1),
(@no_id, 37, @ei_id, 1),
(@yes_id, 38, @ns_id, 1),
(@yes_id, 39, @ei_id, 1),
(@yes_id, 40, @ns_id, 1),
(@no_id, 41, @ei_id, 1),
(@no_id, 42, @l_id, 1),
(@yes_id, 43, @ns_id, 1),
(@yes_id, 44, @ei_id, 1),
(@yes_id, 45, @ns_id, 1),
(@yes_id, 46, @ei_id, 1),
(@yes_id, 47, @ns_id, 1),
(@no_id, 48, @l_id, 1),
(@yes_id, 49, @ei_id, 1),
(@yes_id, 50, @ns_id, 1),
(@no_id, 51, @ei_id, 1),
(@yes_id, 52, @ns_id, 1),
(@yes_id, 53, @ei_id, 1),
(@no_id, 54, @l_id, 1),
(@yes_id, 55, @ns_id, 1),
(@yes_id, 56, @ei_id, 1),
(@yes_id, 57, @ns_id, 1)
;
